# set language
language: python
# # required for building docker images and running them
# sudo: required
# services:
#   - docker
# install command
install: pip install -r requirements.txt
# run test command
script: py.test -vv
